// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MonobankDbContext))]
    [Migration("20221108122649_AddIdentity")]
    partial class AddIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sum")
                        .HasColumnType("int");

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeTransactionID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2022, 7, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Orest",
                            SenderName = "Kolya",
                            Sum = 370,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Sasha",
                            SenderName = "Vlad",
                            Sum = 25000,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Sasha",
                            SenderName = "Vlad",
                            Sum = 25000,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2015, 7, 15, 11, 43, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Transfer money to internet card",
                            RecipientName = "apple.com",
                            SenderName = "Matt Daymon",
                            Sum = 7900,
                            TypeTransactionID = 2
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2022, 1, 11, 19, 23, 22, 0, DateTimeKind.Unspecified),
                            Description = "Charity transfer",
                            RecipientName = "Charity Fund",
                            SenderName = "Jonny Deph",
                            Sum = 1293,
                            TypeTransactionID = 8
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2015, 7, 15, 11, 43, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2022, 1, 11, 19, 23, 22, 0, DateTimeKind.Unspecified),
                            Description = "Charity transfer",
                            RecipientName = "Charity Fund",
                            SenderName = "Jonny Deph",
                            Sum = 1293,
                            TypeTransactionID = 8
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.TypeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TransferToCard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InternetPayment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UtilityCompany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MobileTopUp"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Charity"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cinema"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fines"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.Transaction", b =>
                {
                    b.HasOne("DataAccess.Entities.TypeTransaction", "TypeTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeTransaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.TypeTransaction", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
