// <auto-generated />
using System;
using DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(MonobankDbContext))]
    [Migration("20221106143838_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sum")
                        .HasColumnType("int");

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeTransactionID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2022, 7, 20, 18, 30, 25, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Orest",
                            SenderName = "Kolya",
                            Sum = 370,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Sasha",
                            SenderName = "Vlad",
                            Sum = 25000,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Sasha",
                            SenderName = "Vlad",
                            Sum = 25000,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2015, 7, 15, 11, 43, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Transfer money to internet card",
                            RecipientName = "apple.com",
                            SenderName = "Matt Daymon",
                            Sum = 7900,
                            TypeTransactionID = 2
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2022, 1, 11, 19, 23, 22, 0, DateTimeKind.Unspecified),
                            Description = "Charity transfer",
                            RecipientName = "Charity Fund",
                            SenderName = "Jonny Deph",
                            Sum = 1293,
                            TypeTransactionID = 8
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2015, 7, 15, 11, 43, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Kolya",
                            SenderName = "Orest",
                            Sum = 1232,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2022, 1, 11, 19, 23, 22, 0, DateTimeKind.Unspecified),
                            Description = "Charity transfer",
                            RecipientName = "Charity Fund",
                            SenderName = "Jonny Deph",
                            Sum = 1293,
                            TypeTransactionID = 8
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "On tea",
                            RecipientName = "Vlad",
                            SenderName = "Orest",
                            Sum = 250,
                            TypeTransactionID = 1
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2022, 10, 14, 14, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Shop of clothing",
                            RecipientName = "Shop",
                            SenderName = "Jack Wilston",
                            Sum = 654,
                            TypeTransactionID = 6
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2022, 3, 15, 23, 33, 33, 0, DateTimeKind.Unspecified),
                            Description = "Payment tickets",
                            RecipientName = "MultiplexUA",
                            SenderName = "Matt Colin",
                            Sum = 34,
                            TypeTransactionID = 9
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.TypeTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TransferToCard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InternetPayment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UtilityCompany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MobileTopUp"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Charity"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cinema"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fines"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Transaction", b =>
                {
                    b.HasOne("DataAccess.Entities.TypeTransaction", "TypeTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeTransaction");
                });

            modelBuilder.Entity("DataAccess.Entities.TypeTransaction", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
